### ISSUE TITLE
Update the paper-fab focus like the Material Design spec

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-fab#49]
In the [Floating action button spec](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) there are:

<img width="386" alt="paper-fab" src="https://cloud.githubusercontent.com/assets/1007051/11903563/7e19f9fe-a5ba-11e5-8ddc-f265d072b7cb.png">

And when is focused:

<img width="386" alt="paper-fab_focus" src="https://cloud.githubusercontent.com/assets/1007051/11903573/844d348a-a5ba-11e5-9d49-a581738d0c42.png">

And in the `paper-fab` styles we have:

```css
:host {
  background: var(--paper-fab-background, --accent-color);
}

:host(.keyboard-focus) {
  background: var(--paper-fab-keyboard-focus-background, --paper-pink-900);
}
```

I think that we can improve this, because it looks like a shadow overlaps the `paper-fab`. Harcoded a `--paper-pink-900` background maybe is not the best way.

What do you think? :blush:
